=== imaginegeek57/job4j/chapter_005/src/main/resources/sqlLog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Cars" type="CarsType"/>

    <xs:complexType name="carListType">
        <xs:sequence>
            <xs:element name="id" type="xs:int" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="numberOfCar" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="power" type="xs:int" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CarsType" mixed="true">
        <xs:sequence>
            <xs:element type="carListType" name="carList" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== imaginegeek57/job4j/chapter_005/src/main/resources/sqlLog.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<Cars xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
      xs:noNamespaceSchemaLocation="sqlLog.xsd">

    <carList>
        <id>1</id>
        <name>Авто #1</name>
        <numberOfCar>1</numberOfCar>
        <power>2</power>
        <description>Описание к авто #1</description>
    </carList>
    <carList>
        <id>2</id>
        <name>Авто #2</name>
        <numberOfCar>2</numberOfCar>
        <power>4</power>
        <description>Описание к авто #2</description>
    </carList>
</Cars>
